# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 184737c739be0eedb4626bd0a4a0f5d4a091f7666845c1c74db8720a8513cc16babb9c0fe39a6297bd6ce9222a7065fd616572d7b6ed2747700b87aa4b83f058

test:
  secret_key_base: 94a44613638b4a892c426b7fbd525914b3edf35325939a92833828f72fb159e791cfee8ba59b653b65aea053ff15345b0ad07317693c34b8a3fdec4926266dcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
