# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 079df283fdb756b1d74e701c918ff57cb6ba583c3fa92105523cf5c22dfe04e0e6c0abec49d18ba4b32241f286e8cade0853c21d7b43c968b1a36f1a020ef1e7

test:
  secret_key_base: dd56f9991f3d6b4afa50b427d8f93ad907f7104544cfa47496c84ce801c1d1021c8d1628b26cee60fd78d12517ddc335cb75725b9f289c06a2e3440c54de415e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
